let itemsData = [
  {
    id: "watch1",
    name: "Citizen",
    price: 29900,
    desc: "CITIZEN ECO-DRIVE GENTS BLUE DIAL- CA4213-26L.",
    img: "./images/watch/watch1.jpg",
  },
  {
    id: "watch2",
    name: "Seiko",
    price: 25000,
    desc: "Seiko Men's 5 Sports Automatic 100M Watch.",
    img: "./images/watch/watch2.jpg",
  },
  {
    id: "watch3",
    name: "Rolex",
    price: 1367454,
    desc: "Oyster Perpetual Datejust has continued to reinvent itself.",
    img: "./images/watch/watch3.jpg",
  },
  {
    id: "watch4",
    name: "Omega",
    price: 537508,
    desc: "OMEGA® Swiss Luxury Watches Since 1848.",
    img: "./images/watch/watch4.jpg",
  },
  {
    id: "glass1",
    name: "Arzonai",
    price: 2935,
    desc: "Steampunk Black Sunglasses for Men and Women.",
    img: "./images/eye-glass/glass1.jpg",
  },
  {
    id: "glass2",
    name: "Lacoste",
    price: 9290,
    desc: "L 2274E Metal Frame Unisex.",
    img: "./images/eye-glass/glass2.jpg",
  },
  {
    id: "glass3",
    name: "Ted Smith",
    price: 3500,
    desc: "TS-2090-BLK UV-Protected Full-Rim Sunglasses For Women.",
    img: "./images/eye-glass/glass3.jpg",
  },
  {
    id: "glass4",
    name: "RayBan",
    price: 5800,
    desc: "Fashionable Unique Men Sunglasses Frame Material.",
    img: "./images/eye-glass/glass4.jpg",
  },
  {
    id: "shirt1",
    name: "Nimble made",
    price: 6800,
    desc: "This Dress Shirt | The Crescent.",
    img: "./images/shirt/shirt1.jpg",
  },
  {
    id: "shirt2",
    name: "Nimble made",
    price: 7300,
    desc: "White Collar Speckled Dress Shirt.",
    img: "./images/shirt/shirt2.jpg",
  },

  {
    id: "shirt3",
    name: "Grace Chapel",
    price: 1695,
    desc: "Saved By Grace - Men T-shirts.",
    img: "./images/shirt/shirt3.jpg",
  },
  {
    id: "shirt4",
    name: "Blue Tyga",
    price: 2599,
    desc: "BLUE TYGA Pack of 3 Men Solid Round Neck Multicolor T-Shirt.",
    img: "./images/shirt/shirt4.jpg",
  },
  {
    id: "jeans1",
    name: "Harvard Men",
    price: 1721,
    desc: "Men Black Skinny Fit Mid-Rise Clean Look Stretchable Jeans.",
    img: "./images/jeans/jeans1.jpg",
  },
  {
    id: "jeans2",
    name: "LEVI’S",
    price: 4501,
    desc: "501®The original blue jean since we invented it in 1873.",
    img: "./images/jeans/jeans2.jpg",
  },
  {
    id: "jeans3",
    name: "fourforme",
    price: 3490,
    desc: "fourforme European Style Brand Revival Jeans Men Stretch Elastic.",
    img: "./images/jeans/jeans3.jpg",
  },
  {
    id: "jeans4",
    name: "LEVI’S",
    price: 5300,
    desc: "Levi Strauss We've been innovating to meet people's needs.",
    img: "./images/jeans/jeans4.jpg",
  },
  {
    id: "shoe1",
    name: "Dockers",
    price: 2780,
    desc: "Dockers Rugged Boater Moccasin.",
    img: "./images/shoe/shoe1.jpg",
  },
  {
    id: "shoe2",
    name: "bacca bucci",
    price: 5300,
    desc: "bacca bucci Men Black Sneakers.",
    img: "./images/shoe/shoe2.jpg",
  },
  {
    id: "shoe3",
    name: "Allen Cooper",
    price: 3690,
    desc: "Allen Cooper Men Brown Leather Derbys Casual Shoes.",
    img: "./images/shoe/shoe3.jpg",
  },
  {
    id: "shoe4",
    name: "Highlander",
    price: 3430,
    desc: "Highlander Men White Solid Leather Sneakers.",
    img: "./images/shoe/shoe4.jpg",
  },
  {
    id: "cam1",
    name: "Canon EOS 90D",
    price: 124999,
    desc: "Canon EOS 90D  SLR Camera with 70-300 is USM Lens.",
    img: "./images/camera/cam1.jpg",
  },
  {
    id: "cam2",
    name: "EOS 200D",
    price: 98413,
    desc: "Canon’s Dual Pixel CMOS AF, and a vari-angle LCD .",
    img: "./images/camera/cam2.jpg",
  },
  {
    id: "cam3",
    name: "Nikon D5600",
    price: 91250,
    desc: "Nikon D5600 Digital Camera 18-140mm VR Kit.",
    img: "./images/camera/cam3.jpg",
  },
  {
    id: "cam4",
    name: "Nikon D5500",
    price: 65950,
    desc: "DSLR Camera Body with Single: AF-S 18-140mm VR Kit Lens.",
    img: "./images/camera/cam4.jpg",
  },
  {
    id: "monitor1",
    name: "Dell",
    price: 13990,
    desc: "60.45cm (23.8 inch) monitor beautifully designed.",
    img: "./images/monitor/monitor1.jpg",
  },
  {
    id: "monitor2",
    name: "Asus",
    price: 27999,
    desc: "TUF Gaming VG27AQL1A G-SYNC Gaming Monitor.",
    img: "./images/monitor/monitor2.jpg",
  },
  {
    id: "monitor3",
    name: "Dell UltraSharp",
    price: 102483,
    desc: "Curved USB-C Hub WQHD+ Monitor, Resolution 3840x1600.",
    img: "./images/monitor/monitor3.jpg",
  },
  {
    id: "monitor4",
    name: "View Sonic",
    price: 11599,
    desc: "240Hz 0.5ms MPRT Response Time Blur Gaming Monitor.",
    img: "./images/monitor/monitor4.jpg",
  },
];
